apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggyapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggyapp
  template:
    metadata:
      labels:
        app: buggyapp
    spec:
      containers:
      - name: buggyapp
        image: 242611730375.dkr.ecr.eu-north-1.amazonaws.com/buggyapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buggyapp
    k8s-app: buggyapp
  name: buggyapp-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: buggyapp

